### ISSUE TITLE
Track printed pages

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/www.ubuntu.com#1148]
As mentioned by @yaili, it would be interesting, at the very least, to see how many people are printing pages on our site.

[This article](http://webstandardssherpa.com/reviews/tracking-printed-pages/) outlines a technique for doing this:

``` css
@media print {
  header::after {
    content: url(http://www.google-analytics.com/__utm.gif?
    utmac=UA-XXXXXXX-X&
    utmwv=4.3&
    utmn=2013326124551&
    utmhn=algonquinstudios.com&
    utmr=-&
    utmp=/Engage/Careers&
    utmt=event&
    utme=5%28Print*/Engage/Careers%29&
    utmcc=__utma%3D267504222.1477743002.1364314722.1364314722
    .1364314722.1%3B%2B
    __utmb%3D267504222.17.7.1364314901604%3B%2B
    __utmz%3D267504222.1364314722.1.1.utmcsr%3D%28direct%29
    |utmccn%3D%28direct%29|utmcmd%3D%28none%29);
  }
}
```

Maybe we could add something like this? It looks like this should be quick to do.
