### ISSUE TITLE
Printout of any beta site page is swamped by global navigation

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-websites/www.ubuntu.com#3862]
1\. Go to any page on the beta ubuntu.com site.
2\. View the print preview.

What you see: The first several pages consist of the contents of every navigation flyout, in order.

For example, on the Openstack page, there are _nine_ pages of navigation before the content begins:

![ubuntu com-openstack-print-thumbnails](https://user-images.githubusercontent.com/19801137/43718019-3fd9e1fa-9981-11e8-99cc-0c632109ce1f.png)

What you should see:
- The navigation flyouts should not be included in the printout.
- Probably none of the global navigation should be included at all, except perhaps the Canonical and Ubuntu logos.

**Comment by pmahnke** [comment]
we need to add all the new navigation divs to the print.scss in the display:none section 

``` scss
header,
nav,
footer,
#livechat-compact-view,
.p-top,
.u-hide--small,
.p-heading-icon__img,
.p-contextual-footer {
  display: none;
}
```
